# Tomcat 서버세팅은 Default 값으로 세팅 (Access 로그는 수행시간 패턴 추가)
server:
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 10
    accesslog:
      enabled: true
      directory: c:/dev
      pattern: '%h %l %u %t %r %s %b %D'

# 크롤링 대상 사이트 리스트
target:
    siteList: 
        https://shop.hyundai.com,
        https://www.kia.com,
        https://www.genesis.com